### ISSUE TITLE
Some groups that have not subtitle

### ISSUE THREAD

**Issue by rohmad-st** [qiscus/qiscus-sdk-ios#10]
![Screenshoot](https://trello-attachments.s3.amazonaws.com/5858b5d996496adf97256fbd/5902e625cf5ef06ea675b075/77d8e7fcbfb526844fc221cece5a2a2f/photo.jpg)

**Comment by a-athaullah** [comment]
fixed on commit 182a43a48c9ecf9b44198e4275b0672722d0ceba, and will be added to next release (2.2.10)
