### ISSUE TITLE
Typing indicator in navigation subtitle is annoying

### ISSUE THREAD

**Issue by rohmad-st** [qiscus/qiscus-sdk-ios#11]
ios - ios
- Kadang ada "typing", kadang tidak ada "typing"
- Jika ada "typing", sudah tidak typing tapi masih muncul "typing"

ios - android
- iOS typing, android muncul tanda "typing", tapi setelah sudah tidak typing masih muncul "typing"

baik single chat ataupun group chat

**Comment by a-athaullah** [comment]
fixed on version 2.2.11
