### ISSUE TITLE
Error : Can't load chat room 

### ISSUE THREAD

**Issue by fauzisho** [qiscus/qiscus-sdk-ios#26]
Hi,
I have a problem in open chatroom feature. When I call chatroom, on the top of view showing a dialog : 

> Can't load chat room

what's happen? 
could I get detail of error message?  
for example like delegate or some method call back that to know event message.

Thanks.

**Comment by asharijuang** [comment]
thanks for you report @fauzisho 
1. please make sure your email target is qiscus user already registered.
2. please make sure your app id is correct. You can check your app id in qiscus dashboard.

for next version we will provide some error handling. thanks for your suggestion.
