### ISSUE TITLE
not able to login or register

### ISSUE THREAD

**Issue by mohsinalimat** [qiscus/qiscus-sdk-ios#43]
Hello,

I am not able to login or register with your demo...

**Comment by adicatur** [comment]
hi @mohsinalimat could you share the error message ?

**Comment by mohsinalimat** [comment]
login register result: FAILURE: Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x600000456a40 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=chat-net9ote1xflpceqc.qiscus.com/api/v2/mobile/login_or_register, NSErrorFailingURLKey=chat-net9ote1xflpceqc.qiscus.com/api/v2/mobile/login_or_register, NSLocalizedDescription=unsupported URL}
login url: chat-net9ote1xflpceqc.qiscus.com/api/v2/mobile/login_or_register
post parameters: ["email": abcde@qiscus.coom, "avatar_url": , "username": Steve Kusuma, "password": abcd1234]
post headers: ["QISCUS_SDK_APP_ID": "chat-net9ote1xflpceqc", "User-Agent": "QiscusSDKIos/v2.8.6"]

**Comment by mohsinalimat** [comment]
any updates?

**Comment by mohsinalimat** [comment]
I am not login with your github repo example demo

**Comment by adicatur** [comment]
"Hello,

I am not able to login or register with your demo..."

previously you were not able to login or register with demo, could you try again and let us know the update, hence we could see this issue as a whole 

Thanks you in advance

**Comment by adicatur** [comment]
"Hello,

I am not able to login or register with your demo..."

previously you were not able to login or register with demo, could you try again and let us know the update, hence we could see this issue as a whole 

Thanks you in advance

**Comment by adicatur** [comment]
Hi @mohsinalimat would you like to try this sample https://github.com/qiscus/qiscus-sdk-ios-sample-v2 and let'us know whether this issue still happening or not

Thanks

**Comment by mohsinalimat** [comment]
Hello,

 https://github.com/qiscus/qiscus-sdk-ios-sample-v2

with above url demo I am not login or register please see below issue...

login url: chat-net9ote1xflpceqc.qiscus.com/api/v2/mobile/login_or_register
post parameters: ["email": qqqqqqqqqq, "avatar_url": , "username": qqqqqqqqqq, "password": qqqqqqqqqq]
post headers: ["QISCUS_SDK_APP_ID": "sampleapp-65ghcsaysse", "User-Agent": "QiscusSDKIos/v2.8.6"]
Failed connect. Error: Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x600000641ad0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=chat-net9ote1xflpceqc.qiscus.com/api/v2/mobile/login_or_register, NSErrorFailingURLKey=chat-net9ote1xflpceqc.qiscus.com/api/v2/mobile/login_or_register, NSLocalizedDescription=unsupported URL}

**Comment by evnpr** [comment]
Hi, please make sure you are changing the APP ID in Helpers.swift, I tried using your app id and it works fine. I will close this issue

**Comment by mohsinalimat** [comment]
I have put APP ID in Helpers.swift but not working with your demo...

static var APP_ID: String {
        get {
            return "chat-net9ote1xflpceqc.qiscus.com"
        }
    }

with same error...
