### ISSUE TITLE
Stable version?

### ISSUE THREAD

**Issue by bkrijgsman** [qiscus/qiscus-sdk-ios#45]
What is the most stable version in IOS / Swift 4?
I'm trying to use 2.8.11, but am not able to chat normally.

I see this in de debugger when using the one2one chat
"The data could not be read because it doesn't have the right structure"

Sending an image is ending up in a crash.

**Comment by bkrijgsman** [comment]
Hi asharijuang,

It seems that the deployment could be the issues. The exact same code is working now correctly.
Also no crashes can be reproduced. If you like I can sent a video of the software of yesterday

**Comment by asharijuang** [comment]
thanks for you reports. for next version we will improve our sdk client, and prevent crash when something happen in our server.
yes please, if you have an video. my email juang@qiscus.co or contact.us@qiscus.com
