### ISSUE TITLE
How to get the unread messages?

### ISSUE THREAD

**Issue by SalmanGhumsani** [qiscus/qiscus-sdk-ios#70]
Hello Team,

Hope you are doing well, I need the unread messages as I need to show the unread messages in the notification screen separately.

**Comment by adicatur** [comment]
Hi @SalmanGhumsani for unread count you can get in every object room, but if you want to know your total unread count you can use 
```
Qiscus.getAllUnreadCount(onSuccess: { (unread) in
            print(" unread count " + "\(unread)")
        }) { (error) in
            print("error " + error)
        }
```
By the way, this is not issue hence I will close this 
Thanks for asking :)
